defaults:
  options:
    fallback:
      enabled: true
      values:
        - title: "color"
          values: ["50", "51", "52", "53"]
        - title: "size"
          values: ["S", "M", "L", "XL"]